#pragma once

#include <winioctl.h>

#define PHONEMONITOR_DEVICE_TYPE 0x8000

#define IOCTL_PHONEMONITOR_GET_STATUS CTL_CODE(PHONEMONITOR_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_PHONEMONITOR_ENABLE_DISPLAY CTL_CODE(PHONEMONITOR_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_PHONEMONITOR_DISABLE_DISPLAY CTL_CODE(PHONEMONITOR_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_PHONEMONITOR_SET_MODE CTL_CODE(PHONEMONITOR_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

typedef struct PHONEMONITOR_DISPLAY_MODE
{
    unsigned int Width;
    unsigned int Height;
    unsigned int RefreshRate;
} PHONEMONITOR_DISPLAY_MODE;

typedef struct PHONEMONITOR_DRIVER_STATUS
{
    unsigned int DriverVersion;
    unsigned int DisplayEnabled;
    unsigned int Width;
    unsigned int Height;
    unsigned int RefreshRate;
} PHONEMONITOR_DRIVER_STATUS;
